### ISSUE TITLE
Add simms

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/owlcat#13]

**Comment by gijzelaerr** [comment]
ey Sphe, good work with the PR :)

but there are some issues:
* The simms package doesn't contain a __init__.py file
* you made a simlink to a file in the package, but that doesn't work when you install the package (setup.py install)

**Comment by SpheMakh** [comment]
I've added the init.py file. I just ran  `setup.py install` and the symlink worked. Not sure why its not working for you. I'll cancel the current PR, and redo it.

**Comment by gijzelaerr** [comment]
Hm I'll check tomorrow. You can also undo a commit and  force push to a
branch

Op zo 15 feb. 2015 16:00 schreef Sphesihle Makhathini <
notifications@github.com>:

**Comment by SpheMakh** [comment]
@gijzelaerr Do I need to remake the PR? or will committing the changes on my fork be enough?

**Comment by gijzelaerr** [comment]
You can just push to the branch! :)

Op zo 15 feb. 2015 16:03 schreef Sphesihle Makhathini <
notifications@github.com>:
