### ISSUE TITLE
plot-pointing-errors.py reports no solutions found

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/owlcat#31]
As seen by @SpheMakh.

**Comment by o-smirnov** [comment]
Fix on this branch -- it was  a question of some node names in the Cattery having changed. I added a new ``--prefix`` option to cover these cases:
```
$ plot-pointing-errors.py --prefix EsT0:: Es.fmep
```

**Comment by bennahugo** [comment]
Confirm this works now albeit the plot labelling can do with improvement.
