### ISSUE TITLE
pyfits considered harmful

### ISSUE THREAD

**Issue by mhardcastle** [ska-sa/owlcat#33]
pyfits is deprecated and these days even tells you so itself -- which spams the DDFacet test logs with warning messages since the test suite uses `FitsTool.py`.

pyfits imports should be replaced with

`from astropy.io import fits as pyfits `

**Comment by gijzelaerr** [comment]
should be fixed in this PR https://github.com/ska-sa/owlcat/pull/41

**Comment by gijzelaerr** [comment]
merged
