### ISSUE TITLE
fitstool.py -z option is shifting images

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/owlcat#45]
Tracking down an astrometry offset in a MeerKAT image and of all the things it could be it turns out to be my use of the fitstool.py zoom option to crop the dead regions around a primary beam corrected image. The offset seems to depend on the size of the requested zoom, but appears to shift the spatial axes by the same number of pixels.

Montage's mSubimage tool is a suitable replacement until this is fixed.

![offset](https://user-images.githubusercontent.com/6533799/50610690-ce12cf80-0ecb-11e9-823b-299d4264e675.gif)

**Comment by IanHeywood** [comment]
...this has also been affecting cleaning masks that I generate from wsclean images (8192 x 8192 pixels) and then crop to 8125 x 8125 for use with DDFacet. Drat.

**Comment by o-smirnov** [comment]
Fuck that's embarrassing. Sorry. :(

Guess I don't adjust the WCS right when zooming... lemme fix it...

**Comment by IanHeywood** [comment]
I'm sure I've committed _way_ worse sins. Thanks chief.

**Comment by o-smirnov** [comment]
Fixed on ``issue-45`` branch, can you see if it works for you?

Beware though the printing is somewhat "hobbled" by #46 at the moment.

**Comment by SpheMakh** [comment]
> I'm sure I've committed _way_ worse sins. Thanks chief.


![](https://media.giphy.com/media/l0MYy7QpDDVGVfAAw/giphy.gif)

**Comment by IanHeywood** [comment]
Confirmed to be fixed, thanks. 👍
