### ISSUE TITLE
print statements borked by py3 updates

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/owlcat#46]
See e.g. FitsTool.py. All ``print stuff`` statements turned into the rather useless

```
print()
stuff
```

**Comment by o-smirnov** [comment]
Also, shouldn't there be a ``from __future__ import print_function`` at the top of each file? Otherwise it prints extra ``()`` around each line.

**Comment by gijzelaerr** [comment]
should be fixed per e15e83ac0f67878837169f7c80ce0581c50c38dc, made 1.5.1 release
