### ISSUE TITLE
Add option to ignore missing flags sets if they don't exist instead of raising an exception

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/owlcat#49]

**Comment by o-smirnov** [comment]
OK, so this is for ``flag-ms -r`` I assume, you want it to ignore unknown flagsets, and only remove the known ones.

**Comment by o-smirnov** [comment]
I think it already does just that!

**Comment by o-smirnov** [comment]
Duplicate of #30 

Third time lucky!
