### ISSUE TITLE
make flag-ms.py --stats fast again

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/owlcat#51]
``--stats`` is super-slow, primarily because it re-reads the MS for every flagset. Be smarter!

**Comment by o-smirnov** [comment]
@SpheMakh @sjperkins of course the way to **really** make it fast is with xarray-ms. But for now I have a Simple Kludge(TM).

**Comment by SpheMakh** [comment]
@sjperkins  perfect opportunity to strut your stuff 

![](https://media.giphy.com/media/3o85xwxr06YNoFdSbm/giphy.gif)

**Comment by sjperkins** [comment]
I need context! What needs to happen?

**Comment by SpheMakh** [comment]
@sjperkins we could try xarray-ms/dask to make it faster.

**Comment by o-smirnov** [comment]
Easy, take some ancient code of mine and Make It Fast Again!

It's the ``flag-ms.py`` script for flag management. We actually need a very small subset of features to begin with, so it could be a quick job?

**Comment by o-smirnov** [comment]
> it could be a quick job

(Yeah yeah that's what the HR department said to Sysyphus...)

**Comment by sjperkins** [comment]
Taking a look now, does it only need to update the MS in place (not create a new one)?

**Comment by SpheMakh** [comment]
Nope, it does not create a new MS

**Comment by sjperkins** [comment]
It looks like mostly I/O so wouldn't benefit from compute parallelisation?

**Comment by o-smirnov** [comment]
What it needs to do is open an MS, select a subset, and then do some combination of:

(a) set BITFLAG[FLAG] |= mask ("copy flags to a bitflag")

(b) set FLAG = (BITFLAG&mask) != 0 ("copy bitflags to flags")

(c) set BITFLAG &= mask ("clear some bitflag(s)") 

(d) accumulate bitwise statistics ("how many BITFLAGs in a selection are raised?")

Easy, right?

**Comment by sjperkins** [comment]
In principle, yes.
