### ISSUE TITLE
add --restore of CASA flagversions

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/owlcat#76]
I like CASA flagversions. I don't like having to run CASA to restore them. So: ``flag-ms.py -l`` shall henceforth list flagversions (along with flagsets, if any), and ``flag-ms.py msname -R version`` will restore.

**Comment by IanHeywood** [comment]
+1 for the huge number of beers I owe you.

**Comment by o-smirnov** [comment]
You could make this one beer per line of code, and it wouldn't even be that large a number!
